import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "../firebase/config";
import "tippy.js/dist/tippy.css";
import AuthProvider from "@/context/AppProvider";
import { ToastContainer } from "react-toastify";
import WorkspaceProvider from "@/context/WorkspaceProvider";
import BoardsProvider from "@/context/BoardsProvider";
import ListJobsProvider from "@/context/ListJobsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <WorkspaceProvider>
        <BoardsProvider>
          <ListJobsProvider>
            <html lang="en">
              <body className={inter.className}>
                {children} <ToastContainer />
              </body>
            </html>
          </ListJobsProvider>
        </BoardsProvider>
      </WorkspaceProvider>
    </AuthProvider>
  );
}
